name: Build and deploy Vite React app to Azure Web App - nexalog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # use 18 LTS or compatible

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F9499122B09D4E2498089D1D812ED9BE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EE044E45F988418E82E83AE997027FE6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5C716FC3B3944BE88567C3AA6567FC30 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nexalog'
          slot-name: 'Production'
          package: .
